apiVersion: apps/v1
kind: Deployment

metadata:
  name: ai-app

spec:
  replicas: 3

  strategy:
    type: RollingUpdate

  selector:
    matchLabels:
      app: ai-app

  template:
    metadata:
      labels:
        app: ai-app

    spec:
      containers:
      - name: ai-app
        image: ai-app
        imagePullPolicy: Never

        ports:
        - containerPort: 3000
